const express = require('express')
const routes = express.Router()
const { render } = require('../../helpers/helpers')
const db = require('./database')
const { validate } = require('./validators')
const { admin } = require('../restrictions')
module.exports = routes

// routes.use(admin)
routes.get('/', db.getAll, render('admins', 'Administradores'))
routes.get('/add', render('admins-edit', 'Adicionar administrador'))
routes.get('/edit/:id', validate.id, db.get, render('admins-edit', 'Editar administrador'))
routes.post('/add', validate.add, db.add)
routes.post('/edit/:id', validate.id, validate.edit, db.edit)
routes.get('/remove/:id', validate.id, db.remove)